name: Sync to Local Device

on:
  push:
    branches: [ "main" ]

jobs:
  sync:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3 # Re-verified standard version
        with:
          path: website-content

      - name: Deploy to Target Folder
        run: |
          xcopy /E /Y /I website-content\* "C:\Users\catnolan_senoiahisto\MyWebsite"
